// <copyright file="CreateDeviceRequest.cs" company="APIMatic">
// PagarmeApiSDK.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace PagarmeApiSDK.Standard.Models
{
    /// <summary>
    /// CreateDeviceRequest.
    /// </summary>
    public class CreateDeviceRequest
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateDeviceRequest"/> class.
        /// </summary>
        public CreateDeviceRequest()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CreateDeviceRequest"/> class.
        /// </summary>
        /// <param name="platform">platform.</param>
        public CreateDeviceRequest(
            string platform = "")
        {
            this.Platform = platform;
        }

        /// <summary>
        /// Device's platform
        /// </summary>
        [JsonProperty("platform", NullValueHandling = NullValueHandling.Ignore)]
        public string Platform { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"CreateDeviceRequest : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is CreateDeviceRequest other &&
                (this.Platform == null && other.Platform == null ||
                 this.Platform?.Equals(other.Platform) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Platform = {this.Platform ?? "null"}");
        }
    }
}