// <copyright file="CreateClearSaleRequest.cs" company="APIMatic">
// PagarmeApiSDK.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace PagarmeApiSDK.Standard.Models
{
    /// <summary>
    /// CreateClearSaleRequest.
    /// </summary>
    public class CreateClearSaleRequest
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateClearSaleRequest"/> class.
        /// </summary>
        public CreateClearSaleRequest()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CreateClearSaleRequest"/> class.
        /// </summary>
        /// <param name="customSla">custom_sla.</param>
        public CreateClearSaleRequest(
            int customSla)
        {
            this.CustomSla = customSla;
        }

        /// <summary>
        /// Gets or sets CustomSla.
        /// </summary>
        [JsonProperty("custom_sla")]
        public int CustomSla { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"CreateClearSaleRequest : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is CreateClearSaleRequest other &&
                (this.CustomSla.Equals(other.CustomSla));
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"CustomSla = {this.CustomSla}");
        }
    }
}