// <copyright file="CreateCardOptionsRequest.cs" company="APIMatic">
// PagarmeApiSDK.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace PagarmeApiSDK.Standard.Models
{
    /// <summary>
    /// CreateCardOptionsRequest.
    /// </summary>
    public class CreateCardOptionsRequest
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateCardOptionsRequest"/> class.
        /// </summary>
        public CreateCardOptionsRequest()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CreateCardOptionsRequest"/> class.
        /// </summary>
        /// <param name="verifyCard">verify_card.</param>
        public CreateCardOptionsRequest(
            bool verifyCard)
        {
            this.VerifyCard = verifyCard;
        }

        /// <summary>
        /// Indicates if the card should be verified before creation. If true, executes an authorization before saving the card.
        /// </summary>
        [JsonProperty("verify_card")]
        public bool VerifyCard { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"CreateCardOptionsRequest : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is CreateCardOptionsRequest other &&
                (this.VerifyCard.Equals(other.VerifyCard));
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"VerifyCard = {this.VerifyCard}");
        }
    }
}