// <copyright file="CursorPagingResponse.cs" company="APIMatic">
// PagarmeApiSDK.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace PagarmeApiSDK.Standard.Models
{
    /// <summary>
    /// CursorPagingResponse.
    /// </summary>
    public class CursorPagingResponse
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CursorPagingResponse"/> class.
        /// </summary>
        public CursorPagingResponse()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CursorPagingResponse"/> class.
        /// </summary>
        /// <param name="forwardCursor">forward_cursor.</param>
        public CursorPagingResponse(
            string forwardCursor = "null")
        {
            this.ForwardCursor = forwardCursor;
        }

        /// <summary>
        /// Pagging by foward cursor (https://docs.pagar.me/reference/pagina%C3%A7%C3%A3o-1#forward-cursor)
        /// </summary>
        [JsonProperty("forward_cursor", NullValueHandling = NullValueHandling.Include)]
        public string ForwardCursor { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"CursorPagingResponse : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is CursorPagingResponse other &&
                (this.ForwardCursor == null && other.ForwardCursor == null ||
                 this.ForwardCursor?.Equals(other.ForwardCursor) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"ForwardCursor = {this.ForwardCursor ?? "null"}");
        }
    }
}