// <copyright file="GetPayableResponse.cs" company="APIMatic">
// PagarmeApiSDK.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System;
using System.Collections.Generic;

namespace PagarmeApiSDK.Standard.Models
{
    /// <summary>
    /// GetPayableResponse.
    /// </summary>
    public class GetPayableResponse
    {
        private int? fee;
        private int? anticipationFee;
        private int? fraudCoverageFee;
        private int? installment;
        private string anticipationId;
        private DateTime? paymentDate;
        private string type;
        private DateTime? accrualAt;
        private string liquidationArrangementId;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "fee", false },
            { "anticipation_fee", false },
            { "fraud_coverage_fee", false },
            { "installment", false },
            { "anticipation_id", false },
            { "payment_date", false },
            { "type", false },
            { "accrual_at", false },
            { "liquidation_arrangement_id", true },
        };

        private Dictionary<string, bool> hasPropertySetterCalledFor = new Dictionary<string, bool>
        {
            { "liquidation_arrangement_id", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="GetPayableResponse"/> class.
        /// </summary>
        public GetPayableResponse()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="GetPayableResponse"/> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="status">status.</param>
        /// <param name="amount">amount.</param>
        /// <param name="createdAt">created_at.</param>
        /// <param name="fee">fee.</param>
        /// <param name="anticipationFee">anticipation_fee.</param>
        /// <param name="fraudCoverageFee">fraud_coverage_fee.</param>
        /// <param name="installment">installment.</param>
        /// <param name="gatewayId">gateway_id.</param>
        /// <param name="chargeId">charge_id.</param>
        /// <param name="splitId">split_id.</param>
        /// <param name="bulkAnticipationId">bulk_anticipation_id.</param>
        /// <param name="anticipationId">anticipation_id.</param>
        /// <param name="recipientId">recipient_id.</param>
        /// <param name="originatorModel">originator_model.</param>
        /// <param name="originatorModelId">originator_model_id.</param>
        /// <param name="paymentDate">payment_date.</param>
        /// <param name="originalPaymentDate">original_payment_date.</param>
        /// <param name="type">type.</param>
        /// <param name="paymentMethod">payment_method.</param>
        /// <param name="accrualAt">accrual_at.</param>
        /// <param name="liquidationArrangementId">liquidation_arrangement_id.</param>
        /// <param name="settlementId">settlement_id.</param>
        /// <param name="paymentProfileId">payment_profile_id.</param>
        public GetPayableResponse(
            string id,
            string status,
            int amount,
            DateTime createdAt,
            int? fee = null,
            int? anticipationFee = null,
            int? fraudCoverageFee = null,
            int? installment = null,
            string gatewayId = "null",
            string chargeId = "null",
            string splitId = "null",
            string bulkAnticipationId = "null",
            string anticipationId = "",
            string recipientId = "",
            string originatorModel = "null",
            string originatorModelId = "null",
            DateTime? paymentDate = null,
            DateTime? originalPaymentDate = null,
            string type = "",
            string paymentMethod = "null",
            DateTime? accrualAt = null,
            string liquidationArrangementId = "null",
            string settlementId = "null",
            string paymentProfileId = "null")
        {
            this.Id = id;
            this.Status = status;
            this.Amount = amount;

            if (fee != null)
            {
                this.Fee = fee;
            }

            if (anticipationFee != null)
            {
                this.AnticipationFee = anticipationFee;
            }

            if (fraudCoverageFee != null)
            {
                this.FraudCoverageFee = fraudCoverageFee;
            }

            if (installment != null)
            {
                this.Installment = installment;
            }
            this.GatewayId = gatewayId;
            this.ChargeId = chargeId;
            this.SplitId = splitId;
            this.BulkAnticipationId = bulkAnticipationId;

            if (anticipationId != null)
            {
                this.AnticipationId = anticipationId;
            }
            this.RecipientId = recipientId;
            this.OriginatorModel = originatorModel;
            this.OriginatorModelId = originatorModelId;

            if (paymentDate != null)
            {
                this.PaymentDate = paymentDate;
            }
            this.OriginalPaymentDate = originalPaymentDate;

            if (type != null)
            {
                this.Type = type;
            }
            this.PaymentMethod = paymentMethod;

            if (accrualAt != null)
            {
                this.AccrualAt = accrualAt;
            }
            this.CreatedAt = createdAt;
            this.LiquidationArrangementId = liquidationArrangementId;
            this.SettlementId = settlementId;
            this.PaymentProfileId = paymentProfileId;
        }

        /// <summary>
        /// Payable Identifier
        /// </summary>
        [JsonProperty("id")]
        public string Id { get; set; }

        /// <summary>
        /// Payable status
        /// </summary>
        [JsonProperty("status")]
        public string Status { get; set; }

        /// <summary>
        /// Payable amount in cents
        /// </summary>
        [JsonProperty("amount")]
        public int Amount { get; set; }

        /// <summary>
        /// Payable fee amount in cents
        /// </summary>
        [JsonProperty("fee")]
        public int? Fee
        {
            get
            {
                return this.fee;
            }

            set
            {
                this.shouldSerialize["fee"] = true;
                this.fee = value;
            }
        }

        /// <summary>
        /// Antecipation fee amount in cents
        /// </summary>
        [JsonProperty("anticipation_fee")]
        public int? AnticipationFee
        {
            get
            {
                return this.anticipationFee;
            }

            set
            {
                this.shouldSerialize["anticipation_fee"] = true;
                this.anticipationFee = value;
            }
        }

        /// <summary>
        /// Fraud coverage fee amount in cents
        /// </summary>
        [JsonProperty("fraud_coverage_fee")]
        public int? FraudCoverageFee
        {
            get
            {
                return this.fraudCoverageFee;
            }

            set
            {
                this.shouldSerialize["fraud_coverage_fee"] = true;
                this.fraudCoverageFee = value;
            }
        }

        /// <summary>
        /// Number of installment
        /// </summary>
        [JsonProperty("installment")]
        public int? Installment
        {
            get
            {
                return this.installment;
            }

            set
            {
                this.shouldSerialize["installment"] = true;
                this.installment = value;
            }
        }

        /// <summary>
        /// Payment gateway identifier
        /// </summary>
        [JsonProperty("gateway_id", NullValueHandling = NullValueHandling.Include)]
        public string GatewayId { get; set; }

        /// <summary>
        /// Charge identifier
        /// </summary>
        [JsonProperty("charge_id", NullValueHandling = NullValueHandling.Include)]
        public string ChargeId { get; set; }

        /// <summary>
        /// Gets or sets SplitId.
        /// </summary>
        [JsonProperty("split_id", NullValueHandling = NullValueHandling.Include)]
        public string SplitId { get; set; }

        /// <summary>
        /// Gets or sets BulkAnticipationId.
        /// </summary>
        [JsonProperty("bulk_anticipation_id", NullValueHandling = NullValueHandling.Include)]
        public string BulkAnticipationId { get; set; }

        /// <summary>
        /// Gets or sets AnticipationId.
        /// </summary>
        [JsonProperty("anticipation_id")]
        public string AnticipationId
        {
            get
            {
                return this.anticipationId;
            }

            set
            {
                this.shouldSerialize["anticipation_id"] = true;
                this.anticipationId = value;
            }
        }

        /// <summary>
        /// Recipient identifier
        /// </summary>
        [JsonProperty("recipient_id", NullValueHandling = NullValueHandling.Include)]
        public string RecipientId { get; set; }

        /// <summary>
        /// Gets or sets OriginatorModel.
        /// </summary>
        [JsonProperty("originator_model", NullValueHandling = NullValueHandling.Include)]
        public string OriginatorModel { get; set; }

        /// <summary>
        /// Originator model identifier
        /// </summary>
        [JsonProperty("originator_model_id", NullValueHandling = NullValueHandling.Include)]
        public string OriginatorModelId { get; set; }

        /// <summary>
        /// Payment Date
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("payment_date")]
        public DateTime? PaymentDate
        {
            get
            {
                return this.paymentDate;
            }

            set
            {
                this.shouldSerialize["payment_date"] = true;
                this.paymentDate = value;
            }
        }

        /// <summary>
        /// Original Payment Date
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("original_payment_date", NullValueHandling = NullValueHandling.Include)]
        public DateTime? OriginalPaymentDate { get; set; }

        /// <summary>
        /// Type of payable
        /// </summary>
        [JsonProperty("type")]
        public string Type
        {
            get
            {
                return this.type;
            }

            set
            {
                this.shouldSerialize["type"] = true;
                this.type = value;
            }
        }

        /// <summary>
        /// Payment method of transaction
        /// </summary>
        [JsonProperty("payment_method", NullValueHandling = NullValueHandling.Include)]
        public string PaymentMethod { get; set; }

        /// <summary>
        /// Date issuer identify payment
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("accrual_at")]
        public DateTime? AccrualAt
        {
            get
            {
                return this.accrualAt;
            }

            set
            {
                this.shouldSerialize["accrual_at"] = true;
                this.accrualAt = value;
            }
        }

        /// <summary>
        /// Creation date
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("created_at")]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or sets LiquidationArrangementId.
        /// </summary>
        [JsonProperty("liquidation_arrangement_id")]
        public string LiquidationArrangementId
        {
            get
            {
                if (!hasPropertySetterCalledFor["liquidation_arrangement_id"] &&
                    liquidationArrangementId == null)
                {
                    return "null"; // Default value
                }

                return this.liquidationArrangementId;
            }

            set
            {
                this.shouldSerialize["liquidation_arrangement_id"] = true;
                hasPropertySetterCalledFor["liquidation_arrangement_id"] = true;
                this.liquidationArrangementId = value;
            }
        }

        /// <summary>
        /// Settlement identifier  (new in v7.x)
        /// </summary>
        [JsonProperty("settlement_id", NullValueHandling = NullValueHandling.Include)]
        public string SettlementId { get; set; }

        /// <summary>
        /// Operational identifier of merchant inside of payment platform (new in v7.x)
        /// </summary>
        [JsonProperty("payment_profile_id", NullValueHandling = NullValueHandling.Include)]
        public string PaymentProfileId { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"GetPayableResponse : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetFee()
        {
            this.shouldSerialize["fee"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetAnticipationFee()
        {
            this.shouldSerialize["anticipation_fee"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetFraudCoverageFee()
        {
            this.shouldSerialize["fraud_coverage_fee"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetInstallment()
        {
            this.shouldSerialize["installment"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetAnticipationId()
        {
            this.shouldSerialize["anticipation_id"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetPaymentDate()
        {
            this.shouldSerialize["payment_date"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetType()
        {
            this.shouldSerialize["type"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetAccrualAt()
        {
            this.shouldSerialize["accrual_at"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetLiquidationArrangementId()
        {
            this.shouldSerialize["liquidation_arrangement_id"] = false;
            this.hasPropertySetterCalledFor["liquidation_arrangement_id"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeFee()
        {
            return this.shouldSerialize["fee"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeAnticipationFee()
        {
            return this.shouldSerialize["anticipation_fee"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeFraudCoverageFee()
        {
            return this.shouldSerialize["fraud_coverage_fee"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeInstallment()
        {
            return this.shouldSerialize["installment"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeAnticipationId()
        {
            return this.shouldSerialize["anticipation_id"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializePaymentDate()
        {
            return this.shouldSerialize["payment_date"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeType()
        {
            return this.shouldSerialize["type"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeAccrualAt()
        {
            return this.shouldSerialize["accrual_at"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeLiquidationArrangementId()
        {
            return this.shouldSerialize["liquidation_arrangement_id"];
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is GetPayableResponse other &&
                (this.Id == null && other.Id == null ||
                 this.Id?.Equals(other.Id) == true) &&
                (this.Status == null && other.Status == null ||
                 this.Status?.Equals(other.Status) == true) &&
                (this.Amount.Equals(other.Amount)) &&
                (this.Fee == null && other.Fee == null ||
                 this.Fee?.Equals(other.Fee) == true) &&
                (this.AnticipationFee == null && other.AnticipationFee == null ||
                 this.AnticipationFee?.Equals(other.AnticipationFee) == true) &&
                (this.FraudCoverageFee == null && other.FraudCoverageFee == null ||
                 this.FraudCoverageFee?.Equals(other.FraudCoverageFee) == true) &&
                (this.Installment == null && other.Installment == null ||
                 this.Installment?.Equals(other.Installment) == true) &&
                (this.GatewayId == null && other.GatewayId == null ||
                 this.GatewayId?.Equals(other.GatewayId) == true) &&
                (this.ChargeId == null && other.ChargeId == null ||
                 this.ChargeId?.Equals(other.ChargeId) == true) &&
                (this.SplitId == null && other.SplitId == null ||
                 this.SplitId?.Equals(other.SplitId) == true) &&
                (this.BulkAnticipationId == null && other.BulkAnticipationId == null ||
                 this.BulkAnticipationId?.Equals(other.BulkAnticipationId) == true) &&
                (this.AnticipationId == null && other.AnticipationId == null ||
                 this.AnticipationId?.Equals(other.AnticipationId) == true) &&
                (this.RecipientId == null && other.RecipientId == null ||
                 this.RecipientId?.Equals(other.RecipientId) == true) &&
                (this.OriginatorModel == null && other.OriginatorModel == null ||
                 this.OriginatorModel?.Equals(other.OriginatorModel) == true) &&
                (this.OriginatorModelId == null && other.OriginatorModelId == null ||
                 this.OriginatorModelId?.Equals(other.OriginatorModelId) == true) &&
                (this.PaymentDate == null && other.PaymentDate == null ||
                 this.PaymentDate?.Equals(other.PaymentDate) == true) &&
                (this.OriginalPaymentDate == null && other.OriginalPaymentDate == null ||
                 this.OriginalPaymentDate?.Equals(other.OriginalPaymentDate) == true) &&
                (this.Type == null && other.Type == null ||
                 this.Type?.Equals(other.Type) == true) &&
                (this.PaymentMethod == null && other.PaymentMethod == null ||
                 this.PaymentMethod?.Equals(other.PaymentMethod) == true) &&
                (this.AccrualAt == null && other.AccrualAt == null ||
                 this.AccrualAt?.Equals(other.AccrualAt) == true) &&
                (this.CreatedAt.Equals(other.CreatedAt)) &&
                (this.LiquidationArrangementId == null && other.LiquidationArrangementId == null ||
                 this.LiquidationArrangementId?.Equals(other.LiquidationArrangementId) == true) &&
                (this.SettlementId == null && other.SettlementId == null ||
                 this.SettlementId?.Equals(other.SettlementId) == true) &&
                (this.PaymentProfileId == null && other.PaymentProfileId == null ||
                 this.PaymentProfileId?.Equals(other.PaymentProfileId) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Id = {this.Id ?? "null"}");
            toStringOutput.Add($"Status = {this.Status ?? "null"}");
            toStringOutput.Add($"Amount = {this.Amount}");
            toStringOutput.Add($"Fee = {(this.Fee == null ? "null" : this.Fee.ToString())}");
            toStringOutput.Add($"AnticipationFee = {(this.AnticipationFee == null ? "null" : this.AnticipationFee.ToString())}");
            toStringOutput.Add($"FraudCoverageFee = {(this.FraudCoverageFee == null ? "null" : this.FraudCoverageFee.ToString())}");
            toStringOutput.Add($"Installment = {(this.Installment == null ? "null" : this.Installment.ToString())}");
            toStringOutput.Add($"GatewayId = {this.GatewayId ?? "null"}");
            toStringOutput.Add($"ChargeId = {this.ChargeId ?? "null"}");
            toStringOutput.Add($"SplitId = {this.SplitId ?? "null"}");
            toStringOutput.Add($"BulkAnticipationId = {this.BulkAnticipationId ?? "null"}");
            toStringOutput.Add($"AnticipationId = {this.AnticipationId ?? "null"}");
            toStringOutput.Add($"RecipientId = {this.RecipientId ?? "null"}");
            toStringOutput.Add($"OriginatorModel = {this.OriginatorModel ?? "null"}");
            toStringOutput.Add($"OriginatorModelId = {this.OriginatorModelId ?? "null"}");
            toStringOutput.Add($"PaymentDate = {(this.PaymentDate == null ? "null" : this.PaymentDate.ToString())}");
            toStringOutput.Add($"OriginalPaymentDate = {(this.OriginalPaymentDate == null ? "null" : this.OriginalPaymentDate.ToString())}");
            toStringOutput.Add($"Type = {this.Type ?? "null"}");
            toStringOutput.Add($"PaymentMethod = {this.PaymentMethod ?? "null"}");
            toStringOutput.Add($"AccrualAt = {(this.AccrualAt == null ? "null" : this.AccrualAt.ToString())}");
            toStringOutput.Add($"CreatedAt = {this.CreatedAt}");
            toStringOutput.Add($"LiquidationArrangementId = {this.LiquidationArrangementId ?? "null"}");
            toStringOutput.Add($"SettlementId = {this.SettlementId ?? "null"}");
            toStringOutput.Add($"PaymentProfileId = {this.PaymentProfileId ?? "null"}");
        }
    }
}