// <copyright file="ListWithdrawals.cs" company="APIMatic">
// PagarmeApiSDK.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace PagarmeApiSDK.Standard.Models
{
    /// <summary>
    /// ListWithdrawals.
    /// </summary>
    public class ListWithdrawals
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ListWithdrawals"/> class.
        /// </summary>
        public ListWithdrawals()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ListWithdrawals"/> class.
        /// </summary>
        /// <param name="data">data.</param>
        /// <param name="paging">paging.</param>
        public ListWithdrawals(
            List<Models.GetWithdrawResponse> data,
            Models.PagingResponse paging)
        {
            this.Data = data;
            this.Paging = paging;
        }

        /// <summary>
        /// The Increments response
        /// </summary>
        [JsonProperty("data")]
        public List<Models.GetWithdrawResponse> Data { get; set; }

        /// <summary>
        /// Paging object
        /// </summary>
        [JsonProperty("paging")]
        public Models.PagingResponse Paging { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ListWithdrawals : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is ListWithdrawals other &&
                (this.Data == null && other.Data == null ||
                 this.Data?.Equals(other.Data) == true) &&
                (this.Paging == null && other.Paging == null ||
                 this.Paging?.Equals(other.Paging) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Data = {(this.Data == null ? "null" : $"[{string.Join(", ", this.Data)} ]")}");
            toStringOutput.Add($"Paging = {(this.Paging == null ? "null" : this.Paging.ToString())}");
        }
    }
}