// <copyright file="ListPayablesResponse.cs" company="APIMatic">
// PagarmeApiSDK.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace PagarmeApiSDK.Standard.Models
{
    /// <summary>
    /// ListPayablesResponse.
    /// </summary>
    public class ListPayablesResponse
    {
        private List<Models.GetPayableResponse> data;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "data", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="ListPayablesResponse"/> class.
        /// </summary>
        public ListPayablesResponse()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ListPayablesResponse"/> class.
        /// </summary>
        /// <param name="paging">paging.</param>
        /// <param name="data">data.</param>
        public ListPayablesResponse(
            Models.CursorPagingResponse paging,
            List<Models.GetPayableResponse> data = null)
        {

            if (data != null)
            {
                this.Data = data;
            }
            this.Paging = paging;
        }

        /// <summary>
        /// The payable object
        /// </summary>
        [JsonProperty("data")]
        public List<Models.GetPayableResponse> Data
        {
            get
            {
                return this.data;
            }

            set
            {
                this.shouldSerialize["data"] = true;
                this.data = value;
            }
        }

        /// <summary>
        /// Cursor paging response
        /// </summary>
        [JsonProperty("paging")]
        public Models.CursorPagingResponse Paging { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ListPayablesResponse : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetData()
        {
            this.shouldSerialize["data"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeData()
        {
            return this.shouldSerialize["data"];
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is ListPayablesResponse other &&
                (this.Data == null && other.Data == null ||
                 this.Data?.Equals(other.Data) == true) &&
                (this.Paging == null && other.Paging == null ||
                 this.Paging?.Equals(other.Paging) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Data = {(this.Data == null ? "null" : $"[{string.Join(", ", this.Data)} ]")}");
            toStringOutput.Add($"Paging = {(this.Paging == null ? "null" : this.Paging.ToString())}");
        }
    }
}