// <copyright file="UpdateChargeDueDateRequest.cs" company="APIMatic">
// PagarmeApiSDK.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System;
using System.Collections.Generic;

namespace PagarmeApiSDK.Standard.Models
{
    /// <summary>
    /// UpdateChargeDueDateRequest.
    /// </summary>
    public class UpdateChargeDueDateRequest
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateChargeDueDateRequest"/> class.
        /// </summary>
        public UpdateChargeDueDateRequest()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateChargeDueDateRequest"/> class.
        /// </summary>
        /// <param name="dueAt">due_at.</param>
        public UpdateChargeDueDateRequest(
            DateTime? dueAt = null)
        {
            this.DueAt = dueAt;
        }

        /// <summary>
        /// The charge's new due date
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("due_at", NullValueHandling = NullValueHandling.Ignore)]
        public DateTime? DueAt { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"UpdateChargeDueDateRequest : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is UpdateChargeDueDateRequest other &&
                (this.DueAt == null && other.DueAt == null ||
                 this.DueAt?.Equals(other.DueAt) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"DueAt = {(this.DueAt == null ? "null" : this.DueAt.ToString())}");
        }
    }
}