// <copyright file="UpdateSubscriptionAffiliationIdRequest.cs" company="APIMatic">
// PagarmeApiSDK.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace PagarmeApiSDK.Standard.Models
{
    /// <summary>
    /// UpdateSubscriptionAffiliationIdRequest.
    /// </summary>
    public class UpdateSubscriptionAffiliationIdRequest
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateSubscriptionAffiliationIdRequest"/> class.
        /// </summary>
        public UpdateSubscriptionAffiliationIdRequest()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateSubscriptionAffiliationIdRequest"/> class.
        /// </summary>
        /// <param name="gatewayAffiliationId">gateway_affiliation_id.</param>
        public UpdateSubscriptionAffiliationIdRequest(
            string gatewayAffiliationId)
        {
            this.GatewayAffiliationId = gatewayAffiliationId;
        }

        /// <summary>
        /// Gets or sets GatewayAffiliationId.
        /// </summary>
        [JsonProperty("gateway_affiliation_id")]
        public string GatewayAffiliationId { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"UpdateSubscriptionAffiliationIdRequest : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is UpdateSubscriptionAffiliationIdRequest other &&
                (this.GatewayAffiliationId == null && other.GatewayAffiliationId == null ||
                 this.GatewayAffiliationId?.Equals(other.GatewayAffiliationId) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"GatewayAffiliationId = {this.GatewayAffiliationId ?? "null"}");
        }
    }
}