// <copyright file="UpdateRecipientCodeRequest.cs" company="APIMatic">
// PagarmeApiSDK.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace PagarmeApiSDK.Standard.Models
{
    /// <summary>
    /// UpdateRecipientCodeRequest.
    /// </summary>
    public class UpdateRecipientCodeRequest
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateRecipientCodeRequest"/> class.
        /// </summary>
        public UpdateRecipientCodeRequest()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateRecipientCodeRequest"/> class.
        /// </summary>
        /// <param name="code">code.</param>
        public UpdateRecipientCodeRequest(
            string code)
        {
            this.Code = code;
        }

        /// <summary>
        /// Code
        /// </summary>
        [JsonProperty("code")]
        public string Code { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"UpdateRecipientCodeRequest : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is UpdateRecipientCodeRequest other &&
                (this.Code == null && other.Code == null ||
                 this.Code?.Equals(other.Code) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Code = {this.Code ?? "null"}");
        }
    }
}