// <copyright file="UpdateSubscriptionDueDaysRequest.cs" company="APIMatic">
// PagarmeApiSDK.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace PagarmeApiSDK.Standard.Models
{
    /// <summary>
    /// UpdateSubscriptionDueDaysRequest.
    /// </summary>
    public class UpdateSubscriptionDueDaysRequest
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateSubscriptionDueDaysRequest"/> class.
        /// </summary>
        public UpdateSubscriptionDueDaysRequest()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateSubscriptionDueDaysRequest"/> class.
        /// </summary>
        /// <param name="boletoDueDays">boleto_due_days.</param>
        public UpdateSubscriptionDueDaysRequest(
            int boletoDueDays)
        {
            this.BoletoDueDays = boletoDueDays;
        }

        /// <summary>
        /// Gets or sets BoletoDueDays.
        /// </summary>
        [JsonProperty("boleto_due_days")]
        public int BoletoDueDays { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"UpdateSubscriptionDueDaysRequest : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is UpdateSubscriptionDueDaysRequest other &&
                (this.BoletoDueDays.Equals(other.BoletoDueDays));
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"BoletoDueDays = {this.BoletoDueDays}");
        }
    }
}