// <copyright file="IPayablesController.cs" company="APIMatic">
// PagarmeApiSDK.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Threading;
using System.Threading.Tasks;

namespace PagarmeApiSDK.Standard.Controllers
{
    /// <summary>
    /// IPayablesController.
    /// </summary>
    public interface IPayablesController
    {
        /// <summary>
        /// GetPayables EndPoint.
        /// </summary>
        /// <param name="type">Optional parameter: Example: .</param>
        /// <param name="splitId">Optional parameter: Example: .</param>
        /// <param name="bulkAnticipationId">Optional parameter: Example: .</param>
        /// <param name="status">Optional parameter: Example: .</param>
        /// <param name="recipientId">Optional parameter: Example: .</param>
        /// <param name="chargeId">Optional parameter: Example: .</param>
        /// <param name="paymentDateUntil">Optional parameter: Example: .</param>
        /// <param name="paymentDateSince">Optional parameter: Example: .</param>
        /// <param name="updatedUntil">Optional parameter: Example: .</param>
        /// <param name="updatedSince">Optional parameter: Example: .</param>
        /// <param name="createdUntil">Optional parameter: Example: .</param>
        /// <param name="createdSince">Optional parameter: Example: .</param>
        /// <param name="liquidationArrangementId">Optional parameter: Example: .</param>
        /// <param name="size">Optional parameter: Example: .</param>
        /// <param name="gatewayId">Optional parameter: Example: .</param>
        /// <returns>Returns the Models.ListPayablesResponse response from the API call.</returns>
        /// <returns>Returns the Models.ListPayablesResponse response from the API call.</returns>
        /// <returns>Returns the Models.ListPayablesResponse response from the API call.</returns>
        Models.ListPayablesResponse GetPayables(
                string type = null,
                string splitId = null,
                string bulkAnticipationId = null,
                string status = null,
                string recipientId = null,
                string chargeId = null,
                string paymentDateUntil = null,
                DateTime? paymentDateSince = null,
                DateTime? updatedUntil = null,
                DateTime? updatedSince = null,
                DateTime? createdUntil = null,
                DateTime? createdSince = null,
                string liquidationArrangementId = null,
                int? size = null,
                long? gatewayId = null);

        /// <summary>
        /// GetPayables EndPoint.
        /// </summary>
        /// <param name="type">Optional parameter: Example: .</param>
        /// <param name="splitId">Optional parameter: Example: .</param>
        /// <param name="bulkAnticipationId">Optional parameter: Example: .</param>
        /// <param name="status">Optional parameter: Example: .</param>
        /// <param name="recipientId">Optional parameter: Example: .</param>
        /// <param name="chargeId">Optional parameter: Example: .</param>
        /// <param name="paymentDateUntil">Optional parameter: Example: .</param>
        /// <param name="paymentDateSince">Optional parameter: Example: .</param>
        /// <param name="updatedUntil">Optional parameter: Example: .</param>
        /// <param name="updatedSince">Optional parameter: Example: .</param>
        /// <param name="createdUntil">Optional parameter: Example: .</param>
        /// <param name="createdSince">Optional parameter: Example: .</param>
        /// <param name="liquidationArrangementId">Optional parameter: Example: .</param>
        /// <param name="size">Optional parameter: Example: .</param>
        /// <param name="gatewayId">Optional parameter: Example: .</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the Models.ListPayablesResponse response from the API call.</returns>
        Task<Models.ListPayablesResponse> GetPayablesAsync(
                string type = null,
                string splitId = null,
                string bulkAnticipationId = null,
                string status = null,
                string recipientId = null,
                string chargeId = null,
                string paymentDateUntil = null,
                DateTime? paymentDateSince = null,
                DateTime? updatedUntil = null,
                DateTime? updatedSince = null,
                DateTime? createdUntil = null,
                DateTime? createdSince = null,
                string liquidationArrangementId = null,
                int? size = null,
                long? gatewayId = null,
                CancellationToken cancellationToken = default);
    }
}