// <copyright file="ITransactionsController.cs" company="APIMatic">
// PagarmeApiSDK.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System.Threading;
using System.Threading.Tasks;

namespace PagarmeApiSDK.Standard.Controllers
{
    /// <summary>
    /// ITransactionsController.
    /// </summary>
    public interface ITransactionsController
    {
        /// <summary>
        /// GetTransaction EndPoint.
        /// </summary>
        /// <param name="transactionId">Required parameter: Example: .</param>
        /// <returns>Returns the Models.GetTransactionResponse response from the API call.</returns>
        /// <returns>Returns the Models.GetTransactionResponse response from the API call.</returns>
        /// <returns>Returns the Models.GetTransactionResponse response from the API call.</returns>
        Models.GetTransactionResponse GetTransaction(
                string transactionId);

        /// <summary>
        /// GetTransaction EndPoint.
        /// </summary>
        /// <param name="transactionId">Required parameter: Example: .</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the Models.GetTransactionResponse response from the API call.</returns>
        Task<Models.GetTransactionResponse> GetTransactionAsync(
                string transactionId,
                CancellationToken cancellationToken = default);
    }
}