// <copyright file="ITransfersController.cs" company="APIMatic">
// PagarmeApiSDK.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System.Threading;
using System.Threading.Tasks;

namespace PagarmeApiSDK.Standard.Controllers
{
    /// <summary>
    /// ITransfersController.
    /// </summary>
    public interface ITransfersController
    {
        /// <summary>
        /// GetTransferById EndPoint.
        /// </summary>
        /// <param name="transferId">Required parameter: Example: .</param>
        /// <returns>Returns the Models.GetTransfer response from the API call.</returns>
        /// <returns>Returns the Models.GetTransfer response from the API call.</returns>
        /// <returns>Returns the Models.GetTransfer response from the API call.</returns>
        Models.GetTransfer GetTransferById(
                string transferId);

        /// <summary>
        /// GetTransferById EndPoint.
        /// </summary>
        /// <param name="transferId">Required parameter: Example: .</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the Models.GetTransfer response from the API call.</returns>
        Task<Models.GetTransfer> GetTransferByIdAsync(
                string transferId,
                CancellationToken cancellationToken = default);

        /// <summary>
        /// CreateTransfer EndPoint.
        /// </summary>
        /// <param name="request">Required parameter: Example: .</param>
        /// <returns>Returns the Models.GetTransfer response from the API call.</returns>
        /// <returns>Returns the Models.GetTransfer response from the API call.</returns>
        /// <returns>Returns the Models.GetTransfer response from the API call.</returns>
        Models.GetTransfer CreateTransfer(
                Models.CreateTransfer request);

        /// <summary>
        /// CreateTransfer EndPoint.
        /// </summary>
        /// <param name="request">Required parameter: Example: .</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the Models.GetTransfer response from the API call.</returns>
        Task<Models.GetTransfer> CreateTransferAsync(
                Models.CreateTransfer request,
                CancellationToken cancellationToken = default);

        /// <summary>
        /// Gets all transfers.
        /// </summary>
        /// <returns>Returns the Models.ListTransfers response from the API call.</returns>
        /// <returns>Returns the Models.ListTransfers response from the API call.</returns>
        /// <returns>Returns the Models.ListTransfers response from the API call.</returns>
        Models.ListTransfers GetTransfers();

        /// <summary>
        /// Gets all transfers.
        /// </summary>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the Models.ListTransfers response from the API call.</returns>
        Task<Models.ListTransfers> GetTransfersAsync(CancellationToken cancellationToken = default);
    }
}