// <copyright file="PayablesController.cs" company="APIMatic">
// PagarmeApiSDK.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core;
using APIMatic.Core.Utilities;
using System;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;

namespace PagarmeApiSDK.Standard.Controllers
{
    /// <summary>
    /// PayablesController.
    /// </summary>
    internal class PayablesController : BaseController, IPayablesController
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PayablesController"/> class.
        /// </summary>
        internal PayablesController(GlobalConfiguration globalConfiguration) : base(globalConfiguration) { }

        /// <summary>
        /// GetPayables EndPoint.
        /// </summary>
        /// <param name="type">Optional parameter: Example: .</param>
        /// <param name="splitId">Optional parameter: Example: .</param>
        /// <param name="bulkAnticipationId">Optional parameter: Example: .</param>
        /// <param name="installment">Optional parameter: Example: .</param>
        /// <param name="status">Optional parameter: Example: .</param>
        /// <param name="recipientId">Optional parameter: Example: .</param>
        /// <param name="amount">Optional parameter: Example: .</param>
        /// <param name="chargeId">Optional parameter: Example: .</param>
        /// <param name="paymentDateUntil">Optional parameter: Example: .</param>
        /// <param name="paymentDateSince">Optional parameter: Example: .</param>
        /// <param name="updatedUntil">Optional parameter: Example: .</param>
        /// <param name="updatedSince">Optional parameter: Example: .</param>
        /// <param name="createdUntil">Optional parameter: Example: .</param>
        /// <param name="createdSince">Optional parameter: Example: .</param>
        /// <param name="liquidationArrangementId">Optional parameter: Example: .</param>
        /// <param name="page">Optional parameter: Example: .</param>
        /// <param name="size">Optional parameter: Example: .</param>
        /// <param name="gatewayId">Optional parameter: Example: .</param>
        /// <returns>Returns the Models.ListPayablesResponse response from the API call.</returns>
        public Models.ListPayablesResponse GetPayables(
                string type = null,
                string splitId = null,
                string bulkAnticipationId = null,
                int? installment = null,
                string status = null,
                string recipientId = null,
                int? amount = null,
                string chargeId = null,
                string paymentDateUntil = null,
                DateTime? paymentDateSince = null,
                DateTime? updatedUntil = null,
                DateTime? updatedSince = null,
                DateTime? createdUntil = null,
                DateTime? createdSince = null,
                string liquidationArrangementId = null,
                int? page = null,
                int? size = null,
                long? gatewayId = null)
            => CoreHelper.RunTask(GetPayablesAsync(type, splitId, bulkAnticipationId, installment, status, recipientId, amount, chargeId, paymentDateUntil, paymentDateSince, updatedUntil, updatedSince, createdUntil, createdSince, liquidationArrangementId, page, size, gatewayId));

        /// <summary>
        /// GetPayables EndPoint.
        /// </summary>
        /// <param name="type">Optional parameter: Example: .</param>
        /// <param name="splitId">Optional parameter: Example: .</param>
        /// <param name="bulkAnticipationId">Optional parameter: Example: .</param>
        /// <param name="installment">Optional parameter: Example: .</param>
        /// <param name="status">Optional parameter: Example: .</param>
        /// <param name="recipientId">Optional parameter: Example: .</param>
        /// <param name="amount">Optional parameter: Example: .</param>
        /// <param name="chargeId">Optional parameter: Example: .</param>
        /// <param name="paymentDateUntil">Optional parameter: Example: .</param>
        /// <param name="paymentDateSince">Optional parameter: Example: .</param>
        /// <param name="updatedUntil">Optional parameter: Example: .</param>
        /// <param name="updatedSince">Optional parameter: Example: .</param>
        /// <param name="createdUntil">Optional parameter: Example: .</param>
        /// <param name="createdSince">Optional parameter: Example: .</param>
        /// <param name="liquidationArrangementId">Optional parameter: Example: .</param>
        /// <param name="page">Optional parameter: Example: .</param>
        /// <param name="size">Optional parameter: Example: .</param>
        /// <param name="gatewayId">Optional parameter: Example: .</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the Models.ListPayablesResponse response from the API call.</returns>
        public async Task<Models.ListPayablesResponse> GetPayablesAsync(
                string type = null,
                string splitId = null,
                string bulkAnticipationId = null,
                int? installment = null,
                string status = null,
                string recipientId = null,
                int? amount = null,
                string chargeId = null,
                string paymentDateUntil = null,
                DateTime? paymentDateSince = null,
                DateTime? updatedUntil = null,
                DateTime? updatedSince = null,
                DateTime? createdUntil = null,
                DateTime? createdSince = null,
                string liquidationArrangementId = null,
                int? page = null,
                int? size = null,
                long? gatewayId = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.ListPayablesResponse>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Get, "/payables")
                  .WithAuth("httpBasic")
                  .Parameters(parameters => parameters
                      .Query(query => query.Setup("type", type))
                      .Query(query => query.Setup("split_id", splitId))
                      .Query(query => query.Setup("bulk_anticipation_id", bulkAnticipationId))
                      .Query(query => query.Setup("installment", installment))
                      .Query(query => query.Setup("status", status))
                      .Query(query => query.Setup("recipient_id", recipientId))
                      .Query(query => query.Setup("amount", amount))
                      .Query(query => query.Setup("charge_id", chargeId))
                      .Query(query => query.Setup("payment_date_until", paymentDateUntil))
                      .Query(query => query.Setup("payment_date_since", paymentDateSince.HasValue ? paymentDateSince.Value.ToString("yyyy'-'MM'-'dd'T'HH':'mm':'ss.FFFFFFFK") : null))
                      .Query(query => query.Setup("updated_until", updatedUntil.HasValue ? updatedUntil.Value.ToString("yyyy'-'MM'-'dd'T'HH':'mm':'ss.FFFFFFFK") : null))
                      .Query(query => query.Setup("updated_since", updatedSince.HasValue ? updatedSince.Value.ToString("yyyy'-'MM'-'dd'T'HH':'mm':'ss.FFFFFFFK") : null))
                      .Query(query => query.Setup("created_until", createdUntil.HasValue ? createdUntil.Value.ToString("yyyy'-'MM'-'dd'T'HH':'mm':'ss.FFFFFFFK") : null))
                      .Query(query => query.Setup("created_since", createdSince.HasValue ? createdSince.Value.ToString("yyyy'-'MM'-'dd'T'HH':'mm':'ss.FFFFFFFK") : null))
                      .Query(query => query.Setup("liquidation_arrangement_id", liquidationArrangementId))
                      .Query(query => query.Setup("page", page))
                      .Query(query => query.Setup("size", size))
                      .Query(query => query.Setup("gateway_id", gatewayId))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);
    }
}